GAME_ZIP64.onButtonPress(GAME_ZIP64.ZIP64ButtonPins.Fire1, GAME_ZIP64.ZIP64ButtonEvents.Down, function () {
    Squirtle_1()
})
function Squirtle_1 () {
    display.setMatrixColor(0, 5, skallfarge_1)
    display.setMatrixColor(0, 6, skallfarge_1)
    display.setMatrixColor(1, 6, skallfarge_1)
    display.setMatrixColor(2, 7, skallfarge_1)
    display.setMatrixColor(3, 2, skallfarge_1)
    display.setMatrixColor(3, 3, skallfarge_1)
    display.setMatrixColor(3, 4, skallfarge_1)
    display.setMatrixColor(3, 6, skallfarge_1)
    display.setMatrixColor(4, 2, skallfarge_1)
    display.setMatrixColor(4, 4, skallfarge_1)
    display.setMatrixColor(5, 2, skallfarge_1)
    display.setMatrixColor(5, 3, skallfarge_1)
    display.setMatrixColor(5, 4, skallfarge_1)
    display.setMatrixColor(5, 7, skallfarge_1)
    display.setMatrixColor(6, 2, skallfarge_1)
    display.setMatrixColor(6, 3, skallfarge_1)
    display.setMatrixColor(6, 4, skallfarge_1)
    display.setMatrixColor(7, 2, skallfarge_2)
    display.setMatrixColor(7, 4, skallfarge_2)
    display.setMatrixColor(4, 3, øyefarge)
    display.setMatrixColor(7, 3, øyefarge)
    display.setMatrixColor(1, 4, skallfarge_1)
    display.setMatrixColor(1, 5, skallfarge_1)
    display.setMatrixColor(2, 3, skallfarge_1)
    display.setMatrixColor(2, 4, skallfarge_1)
    display.setMatrixColor(2, 5, skallfarge_1)
    display.setMatrixColor(2, 6, skallfarge_1)
    display.setMatrixColor(3, 5, skallfarge_2)
    display.setMatrixColor(4, 5, skallfarge_2)
    display.setMatrixColor(4, 6, skallfarge_2)
    display.setMatrixColor(5, 6, skallfarge_2)
    display.setMatrixColor(5, 6, skallfarge_2)
    display.setMatrixColor(6, 5, skallfarge_2)
    display.show()
}
let øyefarge = 0
let skallfarge_2 = 0
let skallfarge_1 = 0
let display: GAME_ZIP64.ZIP64Display = null
display = GAME_ZIP64.createZIP64Display()
display.setBrightness(30)
let hudfarge_1 = GAME_ZIP64.rgb(0, 0, 255)
let hudfarge_2 = GAME_ZIP64.rgb(100, 100, 255)
skallfarge_1 = GAME_ZIP64.rgb(200, 50, 50)
skallfarge_2 = GAME_ZIP64.rgb(255, 200, 200)
øyefarge = GAME_ZIP64.colors(ZipLedColors.White)
